# Generated by Django 5.0.7 on 2024-08-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
