# Generated by Django 5.0.7 on 2024-08-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Contact',
        ),
    ]
