# Generated by Django 5.0.7 on 2024-08-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
